# === METADATA ===
KOSAIO_TOOL_ID="aicaos"
KOSAIO_TOOL_NAME="AICAOS"
KOSAIO_TOOL_DESC="Dedicated Operating System for the AICA (ARM7) Sound Chip"
KOSAIO_TOOL_TAGS=("core" "sound" "aica" "arm" "audio" "driver" "os")
KOSAIO_TOOL_TYPE=("core")
KOSAIO_TOOL_DEPS=("build-essential" "git")

# === SOURCE CONTROL ===
KOSAIO_TOOL_REPO="https://github.com/Shockblast/AICAOS.git"
KOSAIO_TOOL_BRANCH=""

# === BUILD OPTIONS ===
KOSAIO_TOOL_BUILD_SYSTEM="none"
KOSAIO_TOOL_BUILD_DIR=""
KOSAIO_TOOL_BUILD_SUBDIR="."
KOSAIO_TOOL_TOOLCHAIN=""
KOSAIO_TOOL_ARGS=()

# === INSTALLATION ===
KOSAIO_TOOL_INSTALL_METHOD="none"
KOSAIO_TOOL_BINARIES=()
KOSAIO_TOOL_BINARY_SUBDIR=""
KOSAIO_TOOL_INSTALLATION_FOLDER="${KOS_BASE}/addons"
KOSAIO_TOOL_INSTALLATION_LIBDIR="lib/dreamcast"
KOSAIO_TOOL_INSTALLATION_INCLUDEDIR="include/aicaos"

# === PATCHES ===
KOSAIO_TOOL_PATCHES=()

# === UNINSTALL & HEALTH ===
KOSAIO_TOOL_LIBS=(
    "${KOS_BASE}/addons/lib/dreamcast/libaicaos.a"
)
KOSAIO_TOOL_INCLUDE_DIRS=(
    "${KOS_BASE}/addons/include/aicaos"
)

# === RICH MESSAGING ===
KOSAIO_TOOL_INSTALL_CONFIRM=false
KOSAIO_TOOL_POSTINSTALL_MESSAGE="AICAOS deployed to ${KOS_BASE}/addons/. Include headers from addons/include/aicaos/ and link with -laicaos."
KOSAIO_TOOL_BUILD_WARNING=()
KOSAIO_TOOL_INSTALL_WARNING=()
KOSAIO_TOOL_INFO_EXTRA=()
