# === METADATA ===
KOSAIO_TOOL_ID="kos"
KOSAIO_TOOL_NAME="KallistiOS"
KOSAIO_TOOL_DESC="The main open-source SDK for the Sega Dreamcast (Libraries & SDK Core)."
KOSAIO_TOOL_TAGS=("core" "sdk" "kallistios" "os")
KOSAIO_TOOL_TYPE=("core")
KOSAIO_TOOL_DEPS=()

# === SOURCE CONTROL ===
KOSAIO_TOOL_REPO="https://github.com/KallistiOS/KallistiOS.git"
KOSAIO_TOOL_BRANCH="v2.2.x"
KOSAIO_TOOL_CLONE_RECURSIVE=true

# === BUILD OPTIONS ===
KOSAIO_TOOL_BUILD_SYSTEM="make"
KOSAIO_TOOL_BUILD_DIR=""
KOSAIO_TOOL_BUILD_SUBDIR="."
KOSAIO_TOOL_TOOLCHAIN=""
KOSAIO_TOOL_ARGS=()

# === INSTALLATION ===
KOSAIO_TOOL_INSTALL_METHOD="none"
KOSAIO_TOOL_BINARIES=()
KOSAIO_TOOL_BINARY_SUBDIR=""
KOSAIO_TOOL_INSTALLATION_FOLDER="${KOS_DIR}"
KOSAIO_TOOL_INSTALLATION_LIBDIR=""
KOSAIO_TOOL_INSTALLATION_INCLUDEDIR=""

# === PATCHES ===
KOSAIO_TOOL_PATCHES=()

# === UNINSTALL & HEALTH ===
KOSAIO_TOOL_CAN_MAKE_CLEAN=true
KOSAIO_TOOL_LIBS=(
    "${KOS_DIR}/lib/dreamcast/libkallisti.a"
)
KOSAIO_TOOL_INCLUDE_DIRS=(
    "${KOS_DIR}/include"
)

# === RICH MESSAGING ===
KOSAIO_TOOL_INSTALL_CONFIRM=false
KOSAIO_TOOL_POSTINSTALL_MESSAGE="You must reload your shell to apply the new KOS environment variables. Run: ${C_B_CYAN}reload${C_RESET}"
KOSAIO_TOOL_BUILD_WARNING=()
KOSAIO_TOOL_INSTALL_WARNING=()
KOSAIO_TOOL_INFO_EXTRA=()
