# === METADATA ===
KOSAIO_TOOL_ID="libdreamroq"
KOSAIO_TOOL_NAME="libdreamroq"
KOSAIO_TOOL_DESC="RoQ playback library for Dreamcast"
KOSAIO_TOOL_TAGS=("video" "roq" "multimedia" "library")
KOSAIO_TOOL_TYPE=("lib")
KOSAIO_TOOL_DEPS=("build-essential" "git")

# === SOURCE CONTROL ===
KOSAIO_TOOL_REPO="https://github.com/Shockblast/libdreamroq.git"
KOSAIO_TOOL_BRANCH=""

# === BUILD OPTIONS ===
KOSAIO_TOOL_BUILD_SYSTEM="make"
KOSAIO_TOOL_BUILD_DIR=""
KOSAIO_TOOL_BUILD_SUBDIR="."
KOSAIO_TOOL_BUILD_TARGET="defaultall"
KOSAIO_TOOL_TOOLCHAIN=""
KOSAIO_TOOL_ARGS=()

# === INSTALLATION ===
KOSAIO_TOOL_INSTALL_METHOD="none"
KOSAIO_TOOL_BINARIES=()
KOSAIO_TOOL_BINARY_SUBDIR=""
KOSAIO_TOOL_INSTALLATION_FOLDER="${KOS_PORTS}/${KOSAIO_TOOL_ID}"
KOSAIO_TOOL_INSTALLATION_LIBDIR=""
KOSAIO_TOOL_INSTALLATION_INCLUDEDIR=""

# === PATCHES ===
KOSAIO_TOOL_PATCHES=()

# === UNINSTALL & HEALTH ===
KOSAIO_TOOL_DIR_OVERRIDE="${KOS_PORTS}/${KOSAIO_TOOL_ID}"
KOSAIO_TOOL_CAN_MAKE_CLEAN=true
KOSAIO_TOOL_SYMLINKS=("${KOS_PORTS}/include/dreamroq:../${KOSAIO_TOOL_ID}/include")
KOSAIO_TOOL_LIBS=(
    "${KOS_PORTS}/${KOSAIO_TOOL_ID}/libdreamroq.a"
)
KOSAIO_TOOL_INCLUDE_DIRS=(
    "${KOS_PORTS}/include/dreamroq"
)

# === RICH MESSAGING ===
KOSAIO_TOOL_INSTALL_CONFIRM=false
KOSAIO_TOOL_POSTINSTALL_MESSAGE=""
KOSAIO_TOOL_BUILD_WARNING=()
KOSAIO_TOOL_INSTALL_WARNING=()
KOSAIO_TOOL_INFO_EXTRA=()
