# === METADATA ===
KOSAIO_TOOL_ID="sgdk"
KOSAIO_TOOL_NAME="SGDK"
KOSAIO_TOOL_DESC="Sega Genesis Development Kit (C Library & Tools)"
KOSAIO_TOOL_TAGS=("sdk" "genesis" "megadrive" "m68k")
KOSAIO_TOOL_TYPE=("sdk")
KOSAIO_TOOL_DEPS=("openjdk-17-jre" "git" "build-essential")

# === SOURCE CONTROL ===
KOSAIO_TOOL_REPO="https://github.com/Stephane-D/SGDK.git"
KOSAIO_TOOL_BRANCH=""
KOSAIO_TOOL_CLONE_RECURSIVE=true

# === BUILD OPTIONS ===
KOSAIO_TOOL_BUILD_SYSTEM="make"
KOSAIO_TOOL_BUILD_DIR=""
KOSAIO_TOOL_BUILD_SUBDIR="."
KOSAIO_TOOL_TOOLCHAIN=""
KOSAIO_TOOL_ARGS=()

# === INSTALLATION ===
KOSAIO_TOOL_INSTALL_METHOD="none"
KOSAIO_TOOL_BINARIES=()
KOSAIO_TOOL_BINARY_SUBDIR=""
KOSAIO_TOOL_INSTALLATION_FOLDER=""
KOSAIO_TOOL_INSTALLATION_LIBDIR=""
KOSAIO_TOOL_INSTALLATION_INCLUDEDIR=""

# === PATCHES ===
KOSAIO_TOOL_PATCHES=()

# === UNINSTALL & HEALTH ===
KOSAIO_TOOL_LIBS=(
    "${KOSAIO_DIR}/repos/sgdk/lib/libmd.a"
)
KOSAIO_TOOL_INCLUDE_DIRS=()

# === RICH MESSAGING ===
KOSAIO_TOOL_INSTALL_CONFIRM=false
KOSAIO_TOOL_POSTINSTALL_MESSAGE=""
KOSAIO_TOOL_BUILD_WARNING=()
KOSAIO_TOOL_INSTALL_WARNING=()
KOSAIO_TOOL_INFO_EXTRA=()
