#!/bin/bash
# THE CONFIG FILES IS NOT FULLY FUNCTIONAL YET.
# THIS SCRIPT MUST BE CALLED IN THE PROJECT FOLDER.
# example: $(/opt/projects/mygame): install-vscode-settings

set -e # Exit immediately if a command exits with a non-zero status.

# Load global variables and functions
source "${KOSAIO_SCRIPTS}/global"

# Backup .vscode folder if it exists
if [ -d ".vscode" ]; then
	echo "Backing up existing .vscode directory to vscode_bk_prekosaio..."
	# Remove old backup if it exists to avoid mv errors
	rm -rf vscode_bk_prekosaio
	mv .vscode vscode_bk_prekosaio
else
	echo "Make folder .vscode"
	mkdir .vscode
fi

# Copy vscode-settings configuration folder to the project
echo "Copying settings from ${KOSAIO_VSCODE_SETTINGS} to .vscode..."
cp -r ${KOSAIO_VSCODE_SETTINGS}/* .vscode/

kosaio-echo "VS Code settings copied successfully.\n Remember to modify the configuration files in .vscode for your project"